
import img1 from '../assets/itemsImage/img (1).jpg'
import img2 from '../assets/itemsImage/img (2).jpg'
import img3 from '../assets/itemsImage/img (3).jpg'
import img4 from '../assets/itemsImage/img (4).jpg'
import img5 from '../assets/itemsImage/img (5).jpg'
import img6 from '../assets/itemsImage/img (6).jpg'
import img7 from '../assets/itemsImage/img (7).jpg'
import img8 from '../assets/itemsImage/img (8).jpg'
import img9 from '../assets/itemsImage/img (9).jpg'
import img10 from '../assets/itemsImage/img (10).jpg'
import img11 from '../assets/itemsImage/img (11).jpg'
import img12 from '../assets/itemsImage/img (12).jpg'
import img13 from '../assets/itemsImage/img (13).jpg'
import img14 from '../assets/itemsImage/img (14).jpg'
import img15 from '../assets/itemsImage/img (15).jpg'
import img16 from '../assets/itemsImage/img (16).jpg'
import img17 from '../assets/itemsImage/img (17).jpg'
import img18 from '../assets/itemsImage/img (18).jpg'
import img19 from '../assets/itemsImage/img (19).jpg'
import img20 from '../assets/itemsImage/img (20).jpg'
import img21 from '../assets/itemsImage/img (21).jpg'
import img22 from '../assets/itemsImage/img (22).jpg'
import img23 from '../assets/itemsImage/img (23).jpg'
import img24 from '../assets/itemsImage/img (24).jpg'
import img25 from '../assets/itemsImage/img (25).jpg'
import img26 from '../assets/itemsImage/img (26).jpg'
import img27 from '../assets/itemsImage/img (27).jpg'
import img28 from '../assets/itemsImage/img (28).jpg'
import img29 from '../assets/itemsImage/img (29).jpg'
import img30 from '../assets/itemsImage/img (30).jpg'
import img31 from '../assets/itemsImage/img (31).jpg'
import img32 from '../assets/itemsImage/img (32).jpg'





export const cars = [
  { id: 1, name: { EN: "Tesla Model X", BN: "টেসলা মডেল এক্স" }, category: { EN: "Electric", BN: "বৈদ্যুতিক" }, price: "$90,000", image: img1, description: { EN: "Tesla Model X is a state-of-the-art electric SUV with exceptional acceleration, long-range battery, and advanced autonomous driving capabilities. The futuristic Falcon Wing doors enhance style and convenience.", BN: "টেসলা মডেল এক্স হলো অত্যাধুনিক বৈদ্যুতিক SUV যা অসাধারণ ত্বরান্বিত, দীর্ঘ রেঞ্জ ব্যাটারি এবং উন্নত স্বচালিত ড্রাইভিং সুবিধা প্রদান করে। ভবিষ্যতের ফ্যালকন উইং দরজাগুলি স্টাইল এবং সুবিধা বৃদ্ধি করে।" }, colors: ["#000000","#FFFFFF","#FF0000","#1E90FF"], rating: 5 },
  { id: 2, name: { EN: "BMW X5", BN: "বিএমডব্লিউ এক্স৫" }, category: { EN: "Electric", BN: "বৈদ্যুতিক" }, price: "$70,000", image: img2, description: { EN: "BMW X5 combines luxury and performance in a sleek electric SUV. It offers a spacious interior, innovative infotainment system, and a smooth ride for daily commuting and long trips.", BN: "বিএমডব্লিউ এক্স৫ একটি আধুনিক বৈদ্যুতিক SUV যা বিলাসিতা এবং কর্মক্ষমতা একত্রিত করে। এটি প্রশস্ত অভ্যন্তর, উদ্ভাবনী ইনফোটেইনমেন্ট সিস্টেম এবং মসৃণ যাত্রা প্রদান করে।" }, colors: ["#FFFFFF","#0000FF","#808080","#FF6347"], rating: 4 },
  { id: 3, name: { EN: "Mercedes S-Class", BN: "মার্সিডিস এস-ক্লাস" }, category: { EN: "Electric", BN: "বৈদ্যুতিক" }, price: "$120,000", image: img3, description: { EN: "Mercedes S-Class offers unparalleled luxury with cutting-edge technology. Comfortable seating, top-tier audio system, and exceptional safety features make every drive enjoyable.", BN: "মার্সিডিস এস-ক্লাস অসাধারণ বিলাসিতা প্রদান করে এবং সর্বাধুনিক প্রযুক্তি সমৃদ্ধ। আরামদায়ক সিট, উন্নত অডিও সিস্টেম এবং অসাধারণ নিরাপত্তা বৈশিষ্ট্য প্রতিটি যাত্রা আনন্দদায়ক করে।" }, colors: ["#000000","#FFFFFF","#FFD700","#2E8B57"], rating: 5 },
  { id: 4, name: { EN: "Toyota Hilux", BN: "টয়োটা হিলাক্স" }, category: { EN: "Electric", BN: "বৈদ্যুতিক" }, price: "$45,000", image: img4, description: { EN: "Toyota Hilux is a rugged and reliable pickup truck perfect for both work and adventure. Durable design, strong performance, and off-road capability make it versatile.", BN: "টয়োটা হিলাক্স একটি শক্তপোক্ত এবং নির্ভরযোগ্য পিকআপ ট্রাক যা কাজ এবং অ্যাডভেঞ্চারের জন্য উপযুক্ত। টেকসই ডিজাইন, শক্তিশালী কর্মক্ষমতা এবং অফ-রোড ক্ষমতা এটিকে বহুমুখী করে।" }, colors: ["#A52A2A","#000000","#FFFFFF","#4682B4"], rating: 4 },
  { id: 5, name: { EN: "Honda Civic", BN: "হোন্ডা সিভিক" }, category: { EN: "SUV", BN: "এসইউভি" }, price: "$25,000", image: img5, description: { EN: "Honda Civic is a compact and efficient vehicle known for reliability and fuel economy. Comfortable interior and smart technology enhance everyday driving experience.", BN: "হোন্ডা সিভিক একটি কমপ্যাক্ট এবং দক্ষ গাড়ি যা নির্ভরযোগ্যতা এবং জ্বালানির অর্থনীতি জন্য পরিচিত। আরামদায়ক অভ্যন্তর এবং স্মার্ট প্রযুক্তি দৈনন্দিন ড্রাইভিংকে উন্নত করে।" }, colors: ["#0000FF","#FFFFFF","#FF4500","#808080"], rating: 4 },
  { id: 6, name: { EN: "Audi Q7", BN: "অডি কিউ৭" }, category: { EN: "SUV", BN: "এসইউভি" }, price: "$80,000", image: img6, description: { EN: "Audi Q7 combines elegance and performance with spacious seating. Advanced safety systems and quattro all-wheel drive ensure confident driving in all conditions.", BN: "অডি কিউ৭ শোভনতা এবং কর্মক্ষমতা একত্রিত করে। উন্নত নিরাপত্তা ব্যবস্থা এবং কুয়াট্রো অল-হুইল ড্রাইভ সব পরিস্থিতিতে আত্মবিশ্বাসী ড্রাইভিং নিশ্চিত করে।" }, colors: ["#FFFFFF","#000000","#B22222","#2F4F4F"], rating: 5 },
  { id: 7, name: { EN: "Ford Mustang", BN: "ফোর্ড মস্তাং" }, category: { EN: "SUV", BN: "এসইউভি" }, price: "$60,000", image: img7, description: { EN: "Ford Mustang is a legendary muscle car combining power and style. Its thrilling engine, sporty design, and advanced tech make it a dream for car enthusiasts.", BN: "ফোর্ড মস্তাং একটি কিংবদন্তি মাসল কার যা শক্তি এবং স্টাইল একত্রিত করে। উত্তেজনাপূর্ণ ইঞ্জিন, স্পোর্টি ডিজাইন এবং উন্নত প্রযুক্তি এটিকে গাড়ি প্রেমীদের স্বপ্ন করে তোলে।" }, colors: ["#FF0000","#000000","#FFFFFF","#1E90FF"], rating: 5 },
  { id: 8, name: { EN: "Toyota Prius", BN: "টয়োটা প্রিয়াস" }, category: { EN: "Luxury", BN: "লাক্সারি" }, price: "$35,000", image: img8, description: { EN: "Toyota Prius is an eco-friendly hybrid car offering smooth ride and exceptional fuel efficiency. Innovative technology and comfort make it ideal for urban commuting.", BN: "টয়োটা প্রিয়াস একটি পরিবেশ বান্ধব হাইব্রিড গাড়ি যা মসৃণ যাত্রা এবং অসাধারণ জ্বালানির দক্ষতা প্রদান করে। উদ্ভাবনী প্রযুক্তি এবং আরাম শহুরে চলাচলের জন্য উপযুক্ত।" }, colors: ["#00FF00","#000000","#FFFFFF","#FFD700"], rating: 4 },
  { id: 9, name: { EN: "Jeep Wrangler", BN: "জিপ র‍্যাংলার" }, category: { EN: "Luxury", BN: "লাক্সারি" }, price: "$50,000", image: img9, description: { EN: "Jeep Wrangler is the ultimate off-road vehicle with rugged design and reliable performance. Ideal for adventure seekers who crave freedom and exploration.", BN: "জিপ র‍্যাংলার হলো চূড়ান্ত অফ-রোড গাড়ি যার শক্তপোক্ত ডিজাইন এবং নির্ভরযোগ্য কর্মক্ষমতা রয়েছে। অ্যাডভেঞ্চারপ্রেমীদের জন্য আদর্শ।" }, colors: ["#000000","#FFFFFF","#FF6347","#228B22"], rating: 5 },
  { id: 10, name: { EN: "Honda Fit", BN: "হোন্ডা ফিট" }, category: { EN: "Luxury", BN: "লাক্সারি" }, price: "$18,000", image: img10, description: { EN: "Honda Fit is a small yet versatile car perfect for city driving. Its fuel efficiency, compact design, and clever storage solutions make it a practical choice.", BN: "হোন্ডা ফিট ছোট কিন্তু বহুমুখী গাড়ি যা শহরে চলাচলের জন্য উপযুক্ত। জ্বালানি দক্ষতা, কমপ্যাক্ট ডিজাইন এবং সৃজনশীল স্টোরেজ সমাধান এটিকে ব্যবহারিক করে তোলে।" }, colors: ["#FFFFFF","#0000FF","#FF69B4","#808080"], rating: 4 },
  { id: 11, name: { EN: "Tesla Model S", BN: "টেসলা মডেল এস" }, category: { EN: "Electric", BN: "বৈদ্যুতিক" }, price: "$95,000", image: img11, description: { EN: "Tesla Model S is a luxury electric sedan with remarkable range and acceleration. It features cutting-edge autopilot technology and a high-tech interior.", BN: "টেসলা মডেল এস হলো একটি বিলাসবহুল বৈদ্যুতিক সেডান যার অসাধারণ রেঞ্জ এবং ত্বরান্বিত ক্ষমতা রয়েছে। এটি সর্বাধুনিক অটোপাইলট প্রযুক্তি এবং হাই-টেক অভ্যন্তর প্রদান করে।" }, colors: ["#000000","#FFFFFF","#FF0000","#1E90FF"], rating: 5 },
  { id: 12, name: { EN: "Mercedes G-Class", BN: "মার্সিডিস জি-ক্লাস" }, category: { EN: "Diesel", BN: "ডিজেল" }, price: "$130,000", image: img12, description: { EN: "Mercedes G-Class is a legendary off-road SUV combining luxury and rugged performance. Ideal for adventure with top-tier comfort and advanced safety.", BN: "মার্সিডিস জি-ক্লাস হলো একটি কিংবদন্তি অফ-রোড SUV যা বিলাসিতা এবং শক্তিশালী কর্মক্ষমতা একত্রিত করে। অ্যাডভেঞ্চারের জন্য উপযুক্ত।" }, colors: ["#FFFFFF","#000000","#808080","#FFD700"], rating: 5 },
  { id: 13, name: { EN: "Mercedes GLA", BN: "মার্সিডিস জি এল এ" }, category: { EN: "Diesel", BN: "ডিজেল" }, price: "$115,000", image: img13, description: { EN: "Mercedes GLA is a compact luxury SUV offering smooth handling, advanced tech features, and stylish design suitable for urban and highway driving.", BN: "মার্সিডিস জি এল এ একটি কমপ্যাক্ট বিলাসবহুল SUV যা মসৃণ হ্যান্ডলিং, উন্নত প্রযুক্তি বৈশিষ্ট্য এবং স্টাইলিশ ডিজাইন প্রদান করে।" }, colors: ["#0000FF","#FFFFFF","#FF6347","#2E8B57"], rating: 4 },
  { id: 14, name: { EN: "Mercedes C-Class", BN: "মার্সিডিস সি-ক্লাস" }, category: { EN: "Petrol", BN: "পেট্রল" }, price: "$130,000", image: img14, description: { EN: "Mercedes C-Class is a premium sedan combining elegance and performance. Comfortable interior, top-notch audio, and advanced safety technology make it ideal for executives.", BN: "মার্সিডিস সি-ক্লাস হলো একটি প্রিমিয়াম সেডান যা শোভনতা এবং কর্মক্ষমতা একত্রিত করে। আরামদায়ক অভ্যন্তর, উন্নত অডিও এবং নিরাপত্তা প্রযুক্তি এটিকে নির্বাহীদের জন্য আদর্শ করে।" }, colors: ["#FFFFFF","#000000","#FFD700","#FF4500"], rating: 5 },
  { id: 15, name: { EN: "BMW 5 Series", BN: "বিএমডব্লিউ ৫ সিরিজ" }, category: { EN: "Petrol", BN: "পেট্রল" }, price: "$120,000", image: img15, description: { EN: "BMW 5 Series offers sporty driving experience with luxurious features. Smooth performance, intuitive infotainment, and elegant design ensure premium experience.", BN: "বিএমডব্লিউ ৫ সিরিজ স্পোর্টি ড্রাইভিং অভিজ্ঞতা এবং বিলাসবহুল বৈশিষ্ট্য প্রদান করে। মসৃণ কর্মক্ষমতা, ইনফোটেইনমেন্ট এবং স্টাইলিশ ডিজাইন নিশ্চিত করে প্রিমিয়াম অভিজ্ঞতা।" }, colors: ["#000000","#FFFFFF","#FF0000","#1E90FF"], rating: 4 },
  { id: 16, name: { EN: "Mercedes GLE", BN: "মার্সিডিস জি এল ই" }, category: { EN: "Hybrid", BN: "হাইব্রিড" }, price: "$140,000", image: img16, description: { EN: "Mercedes GLE is a hybrid SUV offering powerful performance, advanced safety, and luxury comfort. Perfect for long drives and off-road adventures.", BN: "মার্সিডিস জি এল ই একটি হাইব্রিড SUV যা শক্তিশালী কর্মক্ষমতা, উন্নত নিরাপত্তা এবং বিলাসবহুল আরাম প্রদান করে। দীর্ঘ যাত্রা এবং অফ-রোড অ্যাডভেঞ্চারের জন্য উপযুক্ত।" }, colors: ["#FFFFFF","#000000","#B22222","#2F4F4F"], rating: 5 },
  { id: 17, name: { EN: "Toyota Camry", BN: "টয়োটা ক্যামরি" }, category: { EN: "Hybrid", BN: "হাইব্রিড" }, price: "$80,000", image: img17, description: { EN: "Toyota Camry is a reliable hybrid sedan with great fuel efficiency and smooth ride. Comfortable interior and modern features make it ideal for daily use.", BN: "টয়োটা ক্যামরি একটি নির্ভরযোগ্য হাইব্রিড সেডান যা চমৎকার জ্বালানি দক্ষতা এবং মসৃণ যাত্রা প্রদান করে। আরামদায়ক অভ্যন্তর এবং আধুনিক বৈশিষ্ট্য এটিকে দৈনন্দিন ব্যবহারের জন্য উপযুক্ত করে।" }, colors: ["#FFFFFF","#0000FF","#FFD700","#FF4500"], rating: 4 },
  { id: 18, name: { EN: "Mercedes E-Class", BN: "মার্সিডিস ই-ক্লাস" }, category: { EN: "Sedan", BN: "সেডান" }, price: "$110,000", image: img18, description: { EN: "Mercedes E-Class blends performance, luxury, and technology. Advanced safety, elegant design, and smooth drive provide unmatched experience.", BN: "মার্সিডিস ই-ক্লাস কর্মক্ষমতা, বিলাসিতা এবং প্রযুক্তি একত্রিত করে। উন্নত নিরাপত্তা, স্টাইলিশ ডিজাইন এবং মসৃণ ড্রাইভ অসাধারণ অভিজ্ঞতা প্রদান করে।" }, colors: ["#000000","#FFFFFF","#FF6347","#2E8B57"], rating: 5 },
  { id: 19, name: { EN: "BMW 3 Series", BN: "বিএমডব্লিউ ৩ সিরিজ" }, category: { EN: "Sedan", BN: "সেডান" }, price: "$90,000", image: img19, description: { EN: "BMW 3 Series is a sporty sedan with impressive handling and performance. Modern interior and technology provide a premium driving experience.", BN: "বিএমডব্লিউ ৩ সিরিজ একটি স্পোর্টি সেডান যা চমৎকার হ্যান্ডলিং এবং কর্মক্ষমতা প্রদান করে। আধুনিক অভ্যন্তর এবং প্রযুক্তি প্রিমিয়াম ড্রাইভিং অভিজ্ঞতা দেয়।" }, colors: ["#FFFFFF","#0000FF","#FFD700","#FF4500"], rating: 4 },
  { id: 20, name: { EN: "Mercedes SL", BN: "মার্সিডিস এসএল" }, category: { EN: "Convertible", BN: "কনভার্টিবল" }, price: "$150,000", image: img20, description: { EN: "Mercedes SL is a convertible sports car offering thrilling performance and luxury. Sleek design and advanced features make it a perfect weekend car.", BN: "মার্সিডিস এসএল একটি কনভার্টিবল স্পোর্টস কার যা উত্তেজনাপূর্ণ কর্মক্ষমতা এবং বিলাসিতা প্রদান করে। চমৎকার ডিজাইন এবং উন্নত বৈশিষ্ট্য এটিকে নিখুঁত উইকএন্ড কার করে।" }, colors: ["#FF0000","#FFFFFF","#000000","#1E90FF"], rating: 5 },
  { id: 21, name: { EN: "Porsche 911", BN: "পোরশে ৯১১" }, category: { EN: "Convertible", BN: "কনভার্টিবল" }, price: "$200,000", image: img21, description: { EN: "Porsche 911 is an iconic sports car delivering unmatched driving excitement. Timeless design, top-tier performance, and precise handling make it legendary.", BN: "পোরশে ৯১১ একটি আইকনিক স্পোর্টস কার যা অসাধারণ ড্রাইভিং উত্তেজনা প্রদান করে। চিরন্তন ডিজাইন, সেরা কর্মক্ষমতা এবং নিখুঁত হ্যান্ডলিং এটিকে কিংবদন্তি করে।" }, colors: ["#000000","#FFFFFF","#FF6347","#FFD700"], rating: 5 },
  { id: 22, name: { EN: "Volkswagen Golf", BN: "ভলক্সভাগেন গলফ" }, category: { EN: "Hatchback", BN: "হ্যাচব্যাক" }, price: "$30,000", image: img22, description: { EN: "Volkswagen Golf is a compact hatchback offering comfort, efficiency, and modern technology. Ideal for city driving and weekend trips.", BN: "ভলক্সভাগেন গলফ একটি কমপ্যাক্ট হ্যাচব্যাক যা আরাম, দক্ষতা এবং অসাধারণ ড্রাইভিং উত্তেজনা প্রদান করে। চিরন্তন ডিজাইন, সেরা কর্মক্ষমতা এবং নিখুঁত হ্যান্ডলিং এটিকে কিংবদন্তি করে।" }, colors: ["#000000","#FFFFFF","#FF6347","#FFD700"], rating: 5 },
  { id: 23, name: { EN: "Honda Jazz", BN: "হোন্ডা জাজ" }, category: { EN: "Hatchback", BN: "হ্যাচব্যাক" }, price: "$28,000", image: img23, description: { EN: "Honda Jazz is a versatile hatchback with spacious interior and fuel-efficient engine. Perfect for city commutes and daily driving.", BN: "হোন্ডা জাজ একটি বহুমুখী হ্যাচব্যাক যার প্রশস্ত অভ্যন্তর এবং জ্বালানির কার্যকর ইঞ্জিন রয়েছে। শহুরে চলাচল এবং দৈনন্দিন ড্রাইভিং জন্য উপযুক্ত।" }, colors: ["#FFFFFF","#0000FF","#FF4500","#808080"], rating: 4 },
  { id: 24, name: { EN: "Ford F-150", BN: "ফোর্ড এফ-১৫০" }, category: { EN: "Truck", BN: "ট্রাক" }, price: "$50,000", image: img24, description: { EN: "Ford F-150 is a rugged and powerful pickup truck designed for tough work and off-road adventures. It offers durability and reliability.", BN: "ফোর্ড এফ-১৫০ একটি শক্তপোক্ত এবং শক্তিশালী পিকআপ ট্রাক যা কঠিন কাজ এবং অফ-রোড অ্যাডভেঞ্চারের জন্য ডিজাইন করা হয়েছে। এটি স্থায়িত্ব এবং নির্ভরযোগ্যতা প্রদান করে।" }, colors: ["#000000","#FFFFFF","#FFD700","#A52A2A"], rating: 5 },
  { id: 25, name: { EN: "Toyota Tundra", BN: "টয়োটা টুন্ড্রা" }, category: { EN: "Truck", BN: "ট্রাক" }, price: "$60,000", image: img25, description: { EN: "Toyota Tundra is a full-size pickup offering strong performance and off-road capability. Ideal for work, hauling, and adventure.", BN: "টয়োটা টুন্ড্রা একটি ফুল-সাইজ পিকআপ যা শক্তিশালী কর্মক্ষমতা এবং অফ-রোড ক্ষমতা প্রদান করে। কাজ, মালবাহী এবং অ্যাডভেঞ্চারের জন্য উপযুক্ত।" }, colors: ["#FFFFFF","#000000","#1E90FF","#FF6347"], rating: 4 },
  { id: 26, name: { EN: "Land Rover Defender", BN: "ল্যান্ড রোভার ডিফেন্ডার" }, category: { EN: "Off-Road", BN: "অফ-রোড" }, price: "$90,000", image: img26, description: { EN: "Land Rover Defender is an iconic off-road SUV with advanced terrain capabilities, luxurious interior, and rugged design suitable for any adventure.", BN: "ল্যান্ড রোভার ডিফেন্ডার একটি আইকনিক অফ-রোড SUV যার উন্নত টেরেন ক্ষমতা, বিলাসবহুল অভ্যন্তর এবং শক্তপোক্ত ডিজাইন রয়েছে।" }, colors: ["#000000","#FFFFFF","#228B22","#FFD700"], rating: 5 },
  { id: 27, name: { EN: "Jeep Gladiator", BN: "জিপ গ্লাডিয়েটর" }, category: { EN: "Off-Road", BN: "অফ-রোড" }, price: "$80,000", image: img27, description: { EN: "Jeep Gladiator is a versatile off-road truck offering strong performance, durable design, and advanced safety for adventurous driving.", BN: "জিপ গ্লাডিয়েটর একটি বহুমুখী অফ-রোড ট্রাক যা শক্তিশালী কর্মক্ষমতা, টেকসই ডিজাইন এবং অ্যাডভেঞ্চারী ড্রাইভিং-এর জন্য উন্নত নিরাপত্তা প্রদান করে।" }, colors: ["#FFFFFF","#0000FF","#FF4500","#808080"], rating: 4 },
  { id: 28, name: { EN: "Nissan Leaf", BN: "নিসান লিফ" }, category: { EN: "Electric", BN: "বৈদ্যুতিক" }, price: "$40,000", image: img28, description: { EN: "Nissan Leaf is a fully electric compact car with zero emissions. Efficient, quiet, and equipped with advanced technology for sustainable urban mobility.", BN: "নিসান লিফ একটি সম্পূর্ণ বৈদ্যুতিক কমপ্যাক্ট গাড়ি যা শূন্য নির্গমন প্রদান করে। দক্ষ, নীরব এবং উন্নত প্রযুক্তি সমৃদ্ধ।" }, colors: ["#00FF00","#FFFFFF","#000000","#FFD700"], rating: 4 },
  { id: 29, name: { EN: "Audi A6", BN: "অডি এ৬" }, category: { EN: "Sedan", BN: "সেডান" }, price: "$85,000", image: img29, description: { EN: "Audi A6 is a sophisticated sedan with advanced technology and luxurious interior. Smooth ride, great performance, and premium comfort for everyday use.", BN: "অডি এ৬ একটি পরিশীলিত সেডান যার উন্নত প্রযুক্তি এবং বিলাসবহুল অভ্যন্তর রয়েছে। মসৃণ যাত্রা, চমৎকার কর্মক্ষমতা এবং প্রিমিয়াম আরাম দৈনন্দিন ব্যবহারের জন্য।" }, colors: ["#000000","#FFFFFF","#FF6347","#2E8B57"], rating: 5 },
  { id: 30, name: { EN: "BMW X3", BN: "বিএমডব্লিউ এক্স৩" }, category: { EN: "SUV", BN: "এসইউভি" }, price: "$70,000", image: img30, description: { EN: "BMW X3 is a compact luxury SUV combining sportiness and practicality. Advanced safety, smooth driving, and elegant interior make it a perfect family car.", BN: "বিএমডব্লিউ এক্স৩ একটি কমপ্যাক্ট বিলাসবহুল SUV যা স্পোর্টি এবং ব্যবহারিকতা একত্রিত করে। উন্নত নিরাপত্তা, মসৃণ ড্রাইভ এবং স্টাইলিশ অভ্যন্তর এটিকে একটি নিখুঁত পারিবারিক গাড়ি করে।" }, colors: ["#FFFFFF","#0000FF","#FF0000","#808080"], rating: 4 },
  { id: 31, name: { EN: "Mercedes CLA", BN: "মার্সিডিস সিএলএ" }, category: { EN: "Luxury", BN: "লাক্সারি" }, price: "$95,000", image: img31, description: { EN: "Mercedes CLA is a stylish luxury sedan with sporty performance and advanced tech features. Comfortable cabin and elegant design enhance the driving experience.", BN: "মার্সিডিস সিএলএ একটি স্টাইলিশ লাক্সারি সেডান যা স্পোর্টি পারফরম্যান্স এবং উন্নত প্রযুক্তি বৈশিষ্ট্য প্রদান করে। আরামদায়ক কেবিন এবং স্টাইলিশ ডিজাইন ড্রাইভিং অভিজ্ঞতা উন্নত করে।" }, colors: ["#000000","#FFFFFF","#FFD700","#FF4500"], rating: 5 },
  { id: 32, name: { EN: "Tesla Model 3", BN: "টেসলা মডেল ৩" }, category: { EN: "Electric", BN: "বৈদ্যুতিক" }, price: "$55,000", image: img32, description: { EN: "Tesla Model 3 is a compact electric car offering high efficiency, smart technology, and impressive acceleration. Ideal for city and highway driving.", BN: "টেসলা মডেল ৩ একটি কমপ্যাক্ট বৈদ্যুতিক গাড়ি যা উচ্চ দক্ষতা, স্মার্ট প্রযুক্তি এবং চমৎকার ত্বরান্বিত ক্ষমতা প্রদান করে। শহর এবং হাইওয়ে ড্রাইভিং-এর জন্য উপযুক্ত।" }, colors: ["#FFFFFF","#000000","#FF0000","#1E90FF"], rating: 5 },
];
