import img1 from './assets/allProducts/img (1).jpg';
import img2 from './assets/allProducts/img (2).jpg';
import img3 from './assets/allProducts/img (3).jpg';
import img4 from './assets/allProducts/img (4).jpg';
import img5 from './assets/allProducts/img (5).jpg';
import img6 from './assets/allProducts/img (6).jpg';
import img7 from './assets/allProducts/img (7).jpg';
import img8 from './assets/allProducts/img (8).jpg';
import img9 from './assets/allProducts/img (9).jpg';
import img10 from './assets/allProducts/img (10).jpg';
import img11 from './assets/allProducts/img (11).jpg';
import img12 from './assets/allProducts/img (12).jpg';
import img13 from './assets/allProducts/img (13).jpg';
import img14 from './assets/allProducts/img (14).jpg';
import img15 from './assets/allProducts/img (15).jpg';
import img16 from './assets/allProducts/img (16).jpg';
import img17 from './assets/allProducts/img (17).jpg';
import img18 from './assets/allProducts/img (18).jpg';
import img19 from './assets/allProducts/img (19).jpg';
import img20 from './assets/allProducts/img (20).jpg';
import img21 from './assets/allProducts/img (21).jpg';
import img22 from './assets/allProducts/img (22).jpg';
import img23 from './assets/allProducts/img (23).jpg';
import img24 from './assets/allProducts/img (24).jpg';
import img25 from './assets/allProducts/img (25).jpg';
import img26 from './assets/allProducts/img (26).jpg';
import img27 from './assets/allProducts/img (27).jpg';
import img28 from './assets/allProducts/img (28).jpg';
import img29 from './assets/allProducts/img (29).jpg';
import img30 from './assets/allProducts/img (30).jpg';
import img31 from './assets/allProducts/img (31).jpg';
import img32 from './assets/allProducts/img (32).jpg';
import img33 from './assets/allProducts/img (33).jpg';
import img34 from './assets/allProducts/img (34).jpg';
import img35 from './assets/allProducts/img (35).jpg';
import img36 from './assets/allProducts/img (36).jpg';
import img37 from './assets/allProducts/img (37).jpg';
import img38 from './assets/allProducts/img (38).jpg';
import img39 from './assets/allProducts/img (39).jpg';
import img40 from './assets/allProducts/img (40).jpg';
import img41 from './assets/allProducts/img (41).jpg';
import img42 from './assets/allProducts/img (42).jpg';
import img43 from './assets/allProducts/img (43).jpg';
import img44 from './assets/allProducts/img (44).jpg';
import img45 from './assets/allProducts/img (45).jpg';
import img46 from './assets/allProducts/img (46).jpg';
import img47 from './assets/allProducts/img (47).jpg';
import img48 from './assets/allProducts/img (48).jpg';
import img49 from './assets/allProducts/img (49).jpg';
import img50 from './assets/allProducts/img (50).jpg';
import img51 from './assets/allProducts/img (51).jpg';
import img52 from './assets/allProducts/img (52).jpg';
// import img53 from './assets/allProducts/img (53).jpg';
// import img54 from './assets/allProducts/img (54).jpg';
// import img55 from './assets/allProducts/img (55).jpg';
// import img56 from './assets/allProducts/img (56).jpg';
// import img57 from './assets/allProducts/img (57).jpg';
// import img58 from './assets/allProducts/img (58).jpg';
// import img59 from './assets/allProducts/img (59).jpg';
// import img60 from './assets/allProducts/img (60).jpg';
// import img61 from './assets/allProducts/img (61).jpg';
// import img62 from './assets/allProducts/img (62).jpg';
// import img63 from './assets/allProducts/img (63).jpg';
// import img64 from './assets/allProducts/img (64).jpg';
// import img65 from './assets/allProducts/img (65).jpg';
// import img66 from './assets/allProducts/img (66).jpg';
// import img67 from './assets/allProducts/img (67).jpg';
// import img68 from './assets/allProducts/img (68).jpg';
// import img69 from './assets/allProducts/img (69).jpg';
// import img70 from './assets/allProducts/img (70).jpg';
// import img71 from './assets/allProducts/img (71).jpg';
// import img72 from './assets/allProducts/img (72).jpg';
// import img73 from './assets/allProducts/img (73).jpg';
// import img74 from './assets/allProducts/img (74).jpg';
// import img75 from './assets/allProducts/img (75).jpg';
// import img76 from './assets/allProducts/img (76).jpg';
// import img77 from './assets/allProducts/img (77).jpg';
// import img78 from './assets/allProducts/img (78).jpg';
// import img79 from './assets/allProducts/img (79).jpg';
// import img80 from './assets/allProducts/img (80).jpg';


const products = [
{
id: 1,
name_en: 'Tesla Model S',
name_bn: 'টেসলা মডেল এস',
brand: 'Tesla',
model: 'Model S',
category: 'Electric',
price: 35,
shortDesc_en: 'Premium electric sedan with long range and advanced autopilot features.',
shortDesc_bn: 'দীর্ঘ রেঞ্জ ও উন্নত অটোপাইলট ফিচারের প্রিমিয়াম ইলেকট্রিক সেডান।',
year: 2023,
mileage: '10,000 km',
transmission: 'Automatic',
image: img1,
type: "new",
},
{
id: 2,
name_en: 'BMW X5',
name_bn: 'বিএমডব্লিউ এক্স৫',
brand: 'BMW',
model: 'X5',
category: 'SUV',
price: 28,
shortDesc_en: 'Luxury SUV offering strong performance and a comfortable interior.',
shortDesc_bn: 'শক্তিশালী পারফরম্যান্স ও আরামদায়ক ইন্টেরিয়র সহ লাক্সারি SUV।',
year: 2022,
mileage: '15,000 km',
transmission: 'Automatic',
image: img2,
type: "old",
},
{
id: 3,
name_en: 'Toyota Corolla',
name_bn: 'টয়োটা করোলা',
brand: 'Toyota',
model: 'Corolla',
category: 'Sedan',
price: 18,
shortDesc_en: 'Reliable sedan known for efficiency and low maintenance.',
shortDesc_bn: 'কার্যকর ও কম রক্ষণাবেক্ষণের জন্য পরিচিত নির্ভরযোগ্য সেডান।',
year: 2021,
mileage: '20,000 km',
transmission: 'Manual',
image: img3,
},
{
id: 4,
name_en: 'Audi A6',
name_bn: 'অডি A6',
brand: 'Audi',
model: 'A6',
category: 'Sedan',
price: 32,
shortDesc_en: 'Business-class sedan with modern tech and a refined ride.',
shortDesc_bn: 'আধুনিক প্রযুক্তি ও নরম রাইডের সমন্বয়ে বিজনেস-ক্লাস সেডান।',
year: 2024,
mileage: '5,000 km',
transmission: 'Automatic',
image: img4,
},
{
id: 5,
name_en: 'Mercedes-Benz GLC',
name_bn: 'মার্সিডিজ-বেঞ্জ GLC',
brand: 'Mercedes',
model: 'GLC 300',
category: 'SUV',
price: 40,
shortDesc_en: 'Compact luxury SUV with elegant styling and strong safety systems.',
shortDesc_bn: 'ইলিগ্যান্ট ডিজাইন ও উন্নত সেফটি সিস্টেম সহ লাক্সারি কমপ্যাক্ট SUV।',
year: 2025,
mileage: '3,000 km',
transmission: 'Automatic',
image: img5,
},
{
id: 6,
name_en: 'Porsche 911',
name_bn: 'পোরশে ৯১১',
brand: 'Porsche',
model: '911',
category: 'Coupe',
price: 39,
shortDesc_en: 'Iconic sports car with exhilarating handling and strong power.',
shortDesc_bn: 'দ্রুতগতির নির্মম হ্যান্ডলিং ও শক্তিশালী পারফরম্যান্স বিশিষ্ট স্পোর্টস কার।',
year: 2020,
mileage: '25,000 km',
transmission: 'Automatic',
image: img6,
type: "new",
},
{
id: 7,
name_en: 'Rivian R1T',
name_bn: 'রিভিয়ান R1T',
brand: 'Rivian',
model: 'R1T',
category: 'Truck',
price: 38,
shortDesc_en: 'All-electric pickup built for adventure and off-road capability.',
shortDesc_bn: 'অফ-রোড সক্ষমতা ও অ্যাডভেঞ্চারের জন্য নির্মিত পুরো ইলেকট্রিক পিকআপ।',
year: 2023,
mileage: '7,000 km',
transmission: 'Automatic',
image: img7,
type: "new",
},
{
id: 8,
name_en: 'Lucid Air',
name_bn: 'লুসিড এয়ার',
brand: 'Lucid',
model: 'Air',
category: 'Electric',
price: 37,
shortDesc_en: 'High-efficiency electric sedan with premium interior and range.',
shortDesc_bn: 'উচ্চ কার্যকারিতার ইলেকট্রিক সেডান—প্রিমিয়াম ইন্টেরিয়র ও দীর্ঘ রেঞ্জ।',
year: 2024,
mileage: '2,000 km',
transmission: 'Automatic',
image: img8,
type: "new",
},
{
id: 9,
name_en: 'Ford F-150',
name_bn: 'ফোর্ড F-150',
brand: 'Ford',
model: 'F-150',
category: 'Truck',
price: 25,
shortDesc_en: 'Best-selling pickup with strong towing and utility features.',
shortDesc_bn: 'শক্তিশালী টোয়িং ও ইউটিলিটি ফিচারসহ জনপ্রিয় পিকআপ ট্রাক।',
year: 2019,
mileage: '40,000 km',
transmission: 'Automatic',
image: img9,
},
{
id: 10,
name_en: 'Nissan Altima',
name_bn: 'নিসান আলটিমা',
brand: 'Nissan',
model: 'Altima',
category: 'Sedan',
price: 16,
shortDesc_en: 'Comfortable mid-size sedan with balanced fuel economy.',
shortDesc_bn: 'ভালো ইন্ধন-দক্ষতা ও আরামদায়ক মধ্যমানের সেডান।',
year: 2018,
mileage: '50,000 km',
transmission: 'Automatic',
image: img10,
type: "new",
},
{
id: 11,
name_en: 'Hyundai Sonata',
name_bn: 'হুন্ডাই সোনাটা',
brand: 'Hyundai',
model: 'Sonata',
category: 'Sedan',
price: 14,
shortDesc_en: 'Modern family sedan with strong safety features and comfort.',
shortDesc_bn: 'পারিবারিক ব্যবহারের অনুকূল—সুরক্ষা ও আরামের উপর জোর দেয়।',
year: 2020,
mileage: '30,000 km',
transmission: 'Automatic',
image: img11,
type: "new",
},
{
id: 12,
name_en: 'Kia Sportage',
name_bn: 'কিয়া স্পোর্টেজ',
brand: 'Kia',
model: 'Sportage',
category: 'SUV',
price: 15,
shortDesc_en: 'Compact SUV with good value and modern features.',
shortDesc_bn: 'ভালো ভ্যালু ও আধুনিক ফিচারসহ কমপ্যাক্ট SUV।',
year: 2021,
mileage: '22,000 km',
transmission: 'Automatic',
image: img12,
},
{
id: 13,
name_en: 'Toyota Camry',
name_bn: 'টয়োটা ক্যামরি',
brand: 'Toyota',
model: 'Camry',
category: 'Luxury',
price: 20,
shortDesc_en: 'Popular midsize sedan with durability and comfortable ride.',
shortDesc_bn: 'দীর্ঘস্থায়ী ও আরামদায়ক রাইডের জন্য জনপ্রিয় মধ্যমানের সেডান।',
year: 2022,
mileage: '12,000 km',
transmission: 'Automatic',
image: img13,
type: "new",
},
{
id: 14,
name_en: 'Lamborghini Huracán',
name_bn: 'ল্যাম্বরগিনি হুরাকান',
brand: 'Lamborghini',
model: 'Huracán',
category: 'Luxury',
price: 40,
shortDesc_en: 'Exotic supercar with thrilling performance and design.',
shortDesc_bn: 'উত্তেজক পারফরম্যান্স ও ব্যতিক্রমী ডিজাইনের এক্সোটিক সুপারকার।',
year: 2021,
mileage: '6,000 km',
transmission: 'Automatic',
image: img14,
},
{
id: 15,
name_en: 'Isuzu D-Max',
name_bn: 'ইসুজু D-Max',
brand: 'Isuzu',
model: 'D-Max',
category: 'Truck',
price: 12,
shortDesc_en: 'Durable workhorse pickup, popular in commercial use.',
shortDesc_bn: 'বাণিজ্যিক কাজে জনপ্রিয়, টেকসই ও বিশ্বাসযোগ্য পিকআপ।',
year: 2019,
mileage: '35,000 km',
transmission: 'Manual',
image: img15,
type: "new",
},
{
id: 16,
name_en: 'Mercedes E-Class',
name_bn: 'মার্সিডিজ E-ক্লাস',
brand: 'Mercedes',
model: 'E-Class',
category: 'Luxury',
price: 33,
shortDesc_en: 'Refined executive sedan with luxury appointments and tech.',
shortDesc_bn: 'প্রিমিয়াম ফিনিশ ও আধুনিক প্রযুক্তি সমন্বিত এক্সিকিউটিভ সেডান।',
year: 2023,
mileage: '8,000 km',
transmission: 'Automatic',
image: img16,
type: "new",
},
{
id: 17,
name_en: 'BMW 3 Series',
name_bn: 'বিএমডব্লিউ ৩ সিরিজ',
brand: 'BMW',
model: '3 Series',
category: 'Luxury',
price: 22,
shortDesc_en: 'Sporty sedan known for balanced dynamics and comfort.',
shortDesc_bn: 'খেলোয়াড়ি ড্রাইভিং গুণাবলি ও আরামের সমন্বয়ে একটি সেডান।',
year: 2020,
mileage: '28,000 km',
transmission: 'Automatic',
image: img17,
},
{
id: 18,
name_en: 'Tesla Model 3',
name_bn: 'টেসলা মডেল ৩',
brand: 'Tesla',
model: 'Model 3',
category: 'Luxury',
price: 30,
shortDesc_en: 'Compact electric sedan with excellent range and tech stack.',
shortDesc_bn: 'চমৎকার রেঞ্জ ও উন্নত প্রযুক্তি সম্পন্ন কমপ্যাক্ট ইলেকট্রিক সেডান।',
year: 2024,
mileage: '3,500 km',
transmission: 'Automatic',
image: img18,
},
{
id: 19,
name_en: 'Audi Q7',
name_bn: 'অডি Q7',
brand: 'Audi',
model: 'Q7',
category: 'SUV',
price: 29,
shortDesc_en: 'Spacious premium SUV with advanced infotainment and safety.',
shortDesc_bn: 'প্রিমিয়াম ইন্টেরিয়র, উন্নত ইনফোটেইনমেন্ট ও সেফটি সহ বিস্তৃত SUV।',
year: 2021,
mileage: '18,000 km',
transmission: 'Automatic',
image: img19,
},
{
id: 20,
name_en: 'Porsche Cayenne',
name_bn: 'পোরশে কায়েন',
brand: 'Porsche',
model: 'Cayenne',
category: 'SUV',
price: 36,
shortDesc_en: 'Performance SUV delivering sports-car dynamics with utility.',
shortDesc_bn: 'স্পোর্টস–কার ডাইনামিক্স ও ব্যবহারিকতাকে একত্রিত করা পারফরম্যান্স SUV।',
year: 2022,
mileage: '14,000 km',
transmission: 'Automatic',
image: img20,
type: "new",
},
{
id: 21,
name_en: 'Porsche Cayenne',
name_bn: 'পোরশে কায়েন',
brand: 'Porsche',
model: 'Cayenne',
category: 'Luxury',
price: 26,
shortDesc_en: 'Classic American muscle car with strong acceleration.',
shortDesc_bn: 'শক্তিশালী ত্বরণ ও ক্লাসিক আমেরিকান মাসল-কার বৈশিষ্ট্যযুক্ত।',
year: 2019,
mileage: '27,000 km',
transmission: 'Manual',
image: img21,
},
{
id: 22,
name_en: 'Nissan Leaf',
name_bn: 'নিসান লিফ',
brand: 'Nissan',
model: 'Leaf',
category: 'Electric',
price: 12,
shortDesc_en: 'Affordable electric hatchback ideal for city commuting.',
shortDesc_bn: 'শহর চলাচলের জন্য আদর্শ সাশ্রয়ী ইলেকট্রিক হ্যাচব্যাক।',
year: 2023,
mileage: '9,000 km',
transmission: 'Automatic',
image: img22,
},
{
id: 23,
name_en: 'Hyundai Tucson',
name_bn: 'হুন্ডাই টুসকন',
brand: 'Hyundai',
model: 'Tucson',
category: 'SUV',
price: 17,
shortDesc_en: 'Well-rounded compact SUV with user-friendly tech and comfort.',
shortDesc_bn: 'ব্যবহারবান্ধব প্রযুক্তি ও আরামের সমন্বয়ে একটি পূর্ণাঙ্গ কমপ্যাক্ট SUV।',
year: 2022,
mileage: '16,000 km',
transmission: 'Automatic',
image: img23,
},
{
id: 24,
name_en: 'Kia Forte',
name_bn: 'কিয়া ফোর্টে',
brand: 'Kia',
model: 'Forte',
category: 'Sedan',
price: 13,
shortDesc_en: 'Economical compact sedan with smart features for daily use.',
shortDesc_bn: 'দৈনন্দিন ব্যবহারের জন্য স্মার্ট ফিচারসহ সাশ্রয়ী কমপ্যাক্ট সেডান।',
year: 2018,
mileage: '45,000 km',
transmission: 'Manual',
image: img24,
type: "new",
},
{
id: 25,
name_en: 'Toyota RAV4',
name_bn: 'টয়োটা RAV4',
brand: 'Toyota',
model: 'RAV4',
category: 'SUV',
price: 21,
shortDesc_en: 'Reliable compact SUV with versatile cargo and family space.',
shortDesc_bn: 'বহুমুখী কার্গো স্পেস ও পারিবারিক ব্যবহারের জন্য নির্ভরযোগ্য SUV।',
year: 2024,
mileage: '7,500 km',
transmission: 'Automatic',
image: img25,
},
{
id: 26,
name_en: 'Toyota RAV4',
name_bn: 'টয়োটা RAV4',
brand: 'Toyota',
model: 'RAV4',
category: 'SUV',
price: 21,
shortDesc_en: 'Reliable compact SUV with versatile cargo and family space.',
shortDesc_bn: 'দীর্ঘ রেঞ্জ ও পরিশীলিত ইন্টেরিয়র সহ লুসিডের প্রিমিয়াম সেডান।',
year: 2023,
mileage: '4,000 km',
transmission: 'Automatic',
image: img26,
},
{
id: 27,
name_en: 'Rivian R1S',
name_bn: 'রিভিয়ান R1S',
brand: 'Rivian',
model: 'R1S',
category: 'SUV',
price: 37,
shortDesc_en: 'Electric SUV with strong off-road ability and premium cabin.',
shortDesc_bn: 'অফ-রোড সক্ষমতা ও প্রিমিয়াম কেবিনের সমন্বয়ে ইলেকট্রিক SUV।',
year: 2024,
mileage: '3,200 km',
transmission: 'Automatic',
image: img27,
type: "new",
},
{
id: 28,
name_en: 'Porsche Panamera',
name_bn: 'পোরশে প্যানামেরা',
brand: 'Porsche',
model: 'Panamera',
category: 'Sedan',
price: 35,
shortDesc_en: 'Sport-luxury sedan blending daily usability and track-capable performance.',
shortDesc_bn: 'দৈনন্দিন ব্যবহার ও ট্র্যাক-ক্ষমতাসম্পন্ন পারফরম্যান্সের সমন্বয় লাক্সারি সেডান।',
year: 2021,
mileage: '11,000 km',
transmission: 'Automatic',
image: img28,
type: "new",
},
{
id: 29,
name_en: 'Mercedes G-Class',
name_bn: 'মার্সিডিজ জি-ক্লাস',
brand: 'Mercedes',
model: 'G-Class',
category: 'SUV',
price: 40,
shortDesc_en: 'Iconic luxury off-roader with commanding presence and comfort.',
shortDesc_bn: 'উচ্চমানের আরাম ও দাপটপূর্ণ উপস্থিতি সম্পন্ন বিখ্যাত অফ-রোডার।',
year: 2020,
mileage: '20,000 km',
transmission: 'Automatic',
image: img29,
type: "new",
},
{
id: 30,
name_en: 'BMW X3',
name_bn: 'বিএমডব্লিউ এক্স৩',
brand: 'BMW',
model: 'X3',
category: 'SUV',
price: 23,
shortDesc_en: 'Balanced compact luxury SUV with agile handling.',
shortDesc_bn: 'চটপট হ্যান্ডলিং ও সমতাপূর্ণ পারফরম্যান্সের কমপ্যাক্ট লাক্সারি SUV।',
year: 2022,
mileage: '13,000 km',
transmission: 'Automatic',
image: img30,
type: "new",
},
{
id: 31,
name_en: 'Tesla Model X',
name_bn: 'টেসলা মডেল এক্স',
brand: 'Tesla',
model: 'Model X',
category: 'Electric',
price: 39,
shortDesc_en: 'Spacious electric SUV with falcon-wing doors and strong performance.',
shortDesc_bn: 'ফ্যালকন-উইং দরজা ও শক্তিশালী পারফরম্যান্সের বিশাল ইলেকট্রিক SUV।',
year: 2023,
mileage: '6,000 km',
transmission: 'Automatic',
image: img31,
type: "new",
},
{
id: 32,
name_en: 'Audi A4',
name_bn: 'অডি A4',
brand: 'Audi',
model: 'A4',
category: 'Sedan',
price: 19,
shortDesc_en: 'Compact executive sedan with refined driving manners.',
shortDesc_bn: 'নরম ড্রাইভিং ধারা ও প্রিমিয়াম ফিলের কমপ্যাক্ট এক্সিকিউটিভ সেডান।',
year: 2019,
mileage: '32,000 km',
transmission: 'Automatic',
image: img32,
},
{
id: 33,
name_en: 'Toyota Prius',
name_bn: 'টয়োটা প্রিয়াস',
brand: 'Toyota',
model: 'Prius',
category: 'Hatchback',
price: 15,
shortDesc_en: 'Efficient hybrid hatchback known for low running costs.',
shortDesc_bn: 'কম চলাচলের খরচের জন্য পরিচিত কার্যকর হাইব্রিড হ্যাচব্যাক।',
year: 2020,
mileage: '29,000 km',
transmission: 'Automatic',
image: img33,
},
{
id: 34,
name_en: 'Nissan GT-R',
name_bn: 'নিসান GT-R',
brand: 'Nissan',
model: 'GT-R',
category: 'Coupe',
price: 36,
shortDesc_en: 'High-performance sports car with legendary acceleration.',
shortDesc_bn: 'প্রচন্ড ত্বরণ ও উচ্চ-পারফরম্যান্সের জন্য পরিচিত স্পোর্টস কার।',
year: 2018,
mileage: '22,000 km',
transmission: 'Automatic',
image: img34,
},
{
id: 35,
name_en: 'Ford Explorer',
name_bn: 'ফোর্ড এক্সপ্লোরার',
brand: 'Ford',
model: 'Explorer',
category: 'SUV',
price: 24,
shortDesc_en: 'Family-friendly three-row SUV with practical features.',
shortDesc_bn: 'পারিবারিক ব্যবহারের উপযোগী তিন-সারি SUV, ব্যবহারিক সুবিধাসহ।',
year: 2021,
mileage: '21,000 km',
transmission: 'Automatic',
image: img35,
},
{
id: 36,
name_en: 'Isuzu MU-X',
name_bn: 'ইসুজু MU-X',
brand: 'Isuzu',
model: 'MU-X',
category: 'SUV',
price: 16,
shortDesc_en: 'Robust SUV designed for durability and load capacity.',
shortDesc_bn: 'টেকসই ও বেশি লোড সামলানোর ক্ষমতার জন্য ডিজাইনকৃত শক্তবান SUV।',
year: 2022,
mileage: '17,000 km',
transmission: 'Automatic',
image: img36,
},
{
id: 37,
name_en: 'Kia Sorento',
name_bn: 'কিয়া সোরেন্টো',
brand: 'Kia',
model: 'Sorento',
category: 'SUV',
price: 18,
shortDesc_en: 'Spacious three-row SUV with modern comfort features.',
shortDesc_bn: 'আধুনিক আরামদায়ক ফিচারসহ বিস্তৃত তিন-সারি SUV।',
year: 2023,
mileage: '10,000 km',
transmission: 'Automatic',
image: img37,
},
{
id: 38,
name_en: 'Hyundai Elantra',
name_bn: 'হুন্ডাই এলান্ট্রা',
brand: 'Hyundai',
model: 'Elantra',
category: 'Sedan',
price: 11,
shortDesc_en: 'Affordable compact sedan featuring efficient engines.',
shortDesc_bn: 'কার্যকর ইঞ্জিনসহ সাশ্রয়ী কমপ্যাক্ট সেডান।',
year: 2019,
mileage: '34,000 km',
transmission: 'Automatic',
image: img38,
},
{
id: 39,
name_en: 'Toyota Highlander',
name_bn: 'টয়োটা হাইল্যান্ডার',
brand: 'Toyota',
model: 'Highlander',
category: 'SUV',
price: 27,
shortDesc_en: 'Reliable family SUV with comfortable seating and cargo space.',
shortDesc_bn: 'আরামদায়ক সিটিং ও পর্যাপ্ত কার্গো স্পেসসহ বিশ্বাসযোগ্য ফ্যামিলি SUV।',
year: 2024,
mileage: '5,500 km',
transmission: 'Automatic',
image: img39,
},
{
id: 40,
name_en: 'Lamborghini Aventador',
name_bn: 'ল্যাম্বরগিনি অ্যাভেন্টাডর',
brand: 'Lamborghini',
model: 'Aventador',
category: 'Coupe',
price: 40,
shortDesc_en: 'Ultra high-performance exotic car with breathtaking specs.',
shortDesc_bn: 'অবিশ্বাস্য স্পেসিফিকেশনসহ আল্ট্রা-হাই পারফরম্যান্স এক্সোটিক কার।',
year: 2020,
mileage: '9,000 km',
transmission: 'Automatic',
image: img40,
},
{
id: 41,
name_en: 'Porsche 718 Cayman',
name_bn: 'পোরশে ৭১৮ কেম্যান',
brand: 'Porsche',
model: '718 Cayman',
category: 'Coupe',
price: 34,
shortDesc_en: 'Driver-focused sports coupe with precise steering and balance.',
shortDesc_bn: 'নির্ভুল স্টিয়ারিং ও ভারসাম্যযুক্ত ড্রাইভার-কেন্দ্রিক স্পোর্টস কুপে।',
year: 2021,
mileage: '8,500 km',
transmission: 'Automatic',
image: img41,
},
{
id: 42,
name_en: 'Mercedes CLA',
name_bn: 'মার্সিডিজ CLA',
brand: 'Mercedes',
model: 'CLA',
category: 'Sedan',
price: 22,
shortDesc_en: 'Stylish compact sedan with upscale features and comfort.',
shortDesc_bn: 'আধুনিক ও আরামদায়ক—উচ্চমানের ফিচারসমৃদ্ধ কমপ্যাক্ট সেডান।',
year: 2019,
mileage: '33,000 km',
transmission: 'Automatic',
image: img42,
},
{
id: 43,
name_en: 'BMW i8',
name_bn: 'বিএমডব্লিউ i8',
brand: 'BMW',
model: 'i8',
category: 'Electric',
price: 39,
shortDesc_en: 'Futuristic hybrid sports car with advanced lightweight design.',
shortDesc_bn: 'হালকা ও অগ্রগামী ডিজাইনের উন্নত হাইব্রিড স্পোর্টস কার।',
year: 2018,
mileage: '28,000 km',
transmission: 'Automatic',
image: img43,
},
{
id: 44,
name_en: 'Nissan Rogue',
name_bn: 'নিসান রগ',
brand: 'Nissan',
model: 'Rogue',
category: 'SUV',
price: 14,
shortDesc_en: 'Compact SUV offering good value and comfortable ride.',
shortDesc_bn: 'ভালো ভ্যালু ও আরামের সমন্বয়ে একটি কমপ্যাক্ট SUV।',
year: 2021,
mileage: '19,000 km',
transmission: 'Automatic',
image: img44,
},
{
id: 45,
name_en: 'Ford Bronco',
name_bn: 'ফোর্ড ব্রঙ্কো',
brand: 'Ford',
model: 'Bronco',
category: 'SUV',
price: 23,
shortDesc_en: 'Rugged off-road SUV with modern convenience features.',
shortDesc_bn: 'আধুনিক সুবিধাসম্পন্ন শক্তিশালী অফ-রোড SUV।',
year: 2022,
mileage: '12,000 km',
transmission: 'Automatic',
image: img45,
},
{
id: 46,
name_en: 'Tesla Roadster',
name_bn: 'টেসলা রোডস্টার',
brand: 'Tesla',
model: 'Roadster',
category: 'Coupe',
price: 40,
shortDesc_en: 'Ultra-fast electric sports car with cutting-edge engineering.',
shortDesc_bn: 'উচ্চগতির ইলেকট্রিক স্পোর্টস কার—অত্যাধুনিক ইঞ্জিনিয়ারিংসহ।',
year: 2025,
mileage: '1,000 km',
transmission: 'Automatic',
image: img46,
type: "old",
},
{
id: 47,
name_en: 'Audi e-tron',
name_bn: 'অডি ই-ট্রোন',
brand: 'Audi',
model: 'e-tron',
category: 'Electric',
price: 32,
shortDesc_en: 'Electric SUV with quiet cabin and advanced driver assistance.',
shortDesc_bn: 'নীরব কেবিন ও উন্নত চালক-সহায়তা ফিচারসহ ইলেকট্রিক SUV।',
year: 2023,
mileage: '6,500 km',
transmission: 'Automatic',
image: img47,
},
{
id: 48,
name_en: 'Lucid Air Pure',
name_bn: 'লুসিড এয়ার পিউর',
brand: 'Lucid',
model: 'Air Pure',
category: 'Electric',
price: 36,
shortDesc_en: 'Accessible Lucid variant with strong range and premium feel.',
shortDesc_bn: 'ভালো রেঞ্জ ও প্রিমিয়াম অনুভূতি প্রদানকারী লুসিডের পাওয়া যায় এমন ভার্সন।',
year: 2022,
mileage: '9,500 km',
transmission: 'Automatic',
image: img48,
type: "old",
},
{
id: 49,
name_en: 'Rivian R1T Adventure',
name_bn: 'রিভিয়ান R1T অ্যাডভেঞ্চার',
brand: 'Rivian',
model: 'R1T Adventure',
category: 'Truck',
price: 35,
shortDesc_en: 'Adventure-focused pickup with durable build and electric range.',
shortDesc_bn: 'অ্যাডভেঞ্চার-মুখী ইলেকট্রিক পিকআপ—টেকসই নির্মাণ ও ভালো রেঞ্জ।',
year: 2023,
mileage: '7,200 km',
transmission: 'Automatic',
image: img49,
type: "old",
},
{
id: 50,
name_en: 'Isuzu D-Max X-Terrain',
name_bn: 'ইসুজু D-Max X-Terrain',
brand: 'Isuzu',
model: 'D-Max X-Terrain',
category: 'Truck',
price: 13,
shortDesc_en: 'Cargo-capable pickup with rugged underpinnings for work and play.',
shortDesc_bn: 'কঠোর ভিত্তি ও প্রচুর কার্গো ক্ষমতা সম্পন্ন বহুমুখী পিকআপ।',
year: 2020,
mileage: '31,000 km',
transmission: 'Manual',
image: img50,
type: "old",
},
{
id: 51,
name_en: 'Toyota Supra',
name_bn: 'টয়োটা সুপ্রা',
brand: 'Toyota',
model: 'Supra',
category: 'Coupe',
price: 29,
shortDesc_en: 'Sport coupe with sharp handling and engaging driving character.',
shortDesc_bn: 'নির্ভুল হ্যান্ডলিং ও আকর্ষণীয় ড্রাইভিং বৈশিষ্ট্যের স্পোর্ট কুপে।',
year: 2021,
mileage: '14,500 km',
transmission: 'Manual',
image: img51,
type: "old",
},
{
id: 52,
name_en: 'Kia EV6',
name_bn: 'কিয়া EV6',
brand: 'Kia',
model: 'EV6',
category: 'Electric',
price: 28,
shortDesc_en: 'Stylish electric crossover with fast charging and balanced ride.',
shortDesc_bn: 'দ্রুত চার্জিং ও ভারসাম্যপূর্ণ রাইডসহ স্টাইলিশ ইলেকট্রিক ক্রসওভার।',
year: 2023,
mileage: '6,000 km',
transmission: 'Automatic',
image: img52,
},
// {
// id: 53,
// name_en: 'Hyundai Ioniq 5',
// name_bn: 'হুন্ডাই আইওনিক ৫',
// brand: 'Hyundai',
// model: 'Ioniq 5',
// category: 'Electric',
// price: 27,
// shortDesc_en: 'Futuristic electric hatch with spacious interior and rapid charging.',
// shortDesc_bn: 'বিস্তৃত কেবিন ও দ্রুত চার্জিং সুবিধাসহ আধুনিক ইলেকট্রিক হ্যাচ।',
// year: 2022,
// mileage: '5,300 km',
// transmission: 'Automatic',
// image: img53,
// type: "old",
// },
// {
//   id: 54,
//   name_en: "Hyundai Ioniq 5",
//   name_bn: 'হুন্ডাই আইওনিক ৫',
//   brand: "Hyundai",
//   model: "Ioniq 5",
//   category: "truck",
// price: 26,
// shortDesc_en: 'Driver-oriented sporty coupe with timeless appeal.',
// shortDesc_bn: 'ড্রাইভার-আধুনিক স্পোর্টি কুপে, সময়জনিত রোমাঞ্চে ভরা।',
// year: 2020,
// mileage: '23,000 km',
// transmission: 'Manual',
// image: img54,
// },
// {
// id: 55,
// name_en: 'Ford Ranger',
// name_bn: 'ফোর্ড রেঞ্জার',
// brand: 'Ford',
// model: 'Ranger',
// category: 'Truck',
// price: 17,
// shortDesc_en: 'Mid-size pickup with good towing and everyday practicality.',
// shortDesc_bn: 'ভালো টোয়িং ক্ষমতা ও দৈনন্দিন ব্যবহার উপযোগী মধ্য-আকার পিকআপ।',
// year: 2019,
// mileage: '36,000 km',
// transmission: 'Manual',
// image: img55,
// type: "old",
// },
// {
// id: 56,
// name_en: 'BMW i4',
// name_bn: 'বিএমডব্লিউ i4',
// brand: 'BMW',
// model: 'i4',
// category: 'Sedan',
// price: 31,
// shortDesc_en: 'Electric sedan combining BMW dynamics with electric efficiency.',
// shortDesc_bn: 'বিএমডব্লিউর ড্রাইভিং স্বতন্ত্রতা ও ইলেকট্রিক দক্ষতার সমন্বয়।',
// year: 2023,
// mileage: '4,500 km',
// transmission: 'Automatic',
// image: img56,
// },
// {
// id: 57,
// name_en: 'Mercedes S-Class',
// name_bn: 'মার্সিডিজ এস-ক্লাস',
// brand: 'Mercedes',
// model: 'S-Class',
// category: 'Sedan',
// price: 40,
// shortDesc_en: 'Flagship luxury sedan with unmatched comfort and tech.',
// shortDesc_bn: 'অসাধারণ আরাম ও উন্নত প্রযুক্তিসম্পন্ন ফ্ল্যাগশিপ লাক্সারি সেডান।',
// year: 2024,
// mileage: '2,200 km',
// transmission: 'Automatic',
// image: img57,
// type: "old",
// },
// {
// id: 58,
// name_en: 'Porsche Macan',
// name_bn: 'পোরশে ম্যাকান',
// brand: 'Porsche',
// model: 'Macan',
// category: 'SUV',
// price: 30,
// shortDesc_en: 'Compact performance SUV with engaging driving dynamics.',
// shortDesc_bn: 'আকর্ষণীয় ড্রাইভিং ডাইনামিক্সের সঙ্গে কমপ্যাক্ট পারফরম্যান্স SUV।',
// year: 2021,
// mileage: '16,700 km',
// transmission: 'Automatic',
// image: img58,
// },
// {
// id: 59,
// name_en: 'Porsche Macan',
// name_bn: 'পোরশে ম্যাকান',
// brand: 'Porsche',
// model: 'Macan',
// category: 'SUV',
// price: 30,
// shortDesc_en: 'Compact performance SUV with engaging driving dynamics.',
// shortDesc_bn: 'উচ্চ পারফরম্যান্স ও এক্সোটিক ডিজাইনের মিশেল—সুপার SUV।',
// year: 2022,
// mileage: '11,000 km',
// transmission: 'Automatic',
// image: img59,
// },
// {
// id: 60,
// name_en: 'Audi TT',
// name_bn: 'অডি TT',
// brand: 'Audi',
// model: 'TT',
// category: 'Coupe',
// price: 21,
// shortDesc_en: 'Compact sports coupe with crisp handling and attractive looks.',
// shortDesc_bn: 'নান্দনিক চেহারা ও তীক্ষ্ণ হ্যান্ডলিংয়ের সমন্বয়ে কমপ্যাক্ট স্পোর্টস কুপে।',
// year: 2018,
// mileage: '39,000 km',
// transmission: 'Manual',
// image: img60,
// type: "old",
// },
// {
// id: 61,
// name_en: 'Toyota Land Cruiser',
// name_bn: 'টয়োটা ল্যান্ড ক্রুজার',
// brand: 'Toyota',
// model: 'Land Cruiser',
// category: 'SUV',
// price: 35,
// shortDesc_en: 'Legendary off-roader built for durability and long-distance travel.',
// shortDesc_bn: 'দীর্ঘ পথ ও কঠোর পরিবেশ সইতে সক্ষম কিংবদন্তি অফ-রোডার।',
// year: 2021,
// mileage: '27,500 km',
// transmission: 'Automatic',
// image: img61,
// },
// {
// id: 62,
// name_en: 'Hyundai Palisade',
// name_bn: 'হুন্ডাই প্যালিসেড',
// brand: 'Hyundai',
// model: 'Palisade',
// category: 'SUV',
// price: 20,
// shortDesc_en: 'Three-row family SUV with generous space and comfort.',
// shortDesc_bn: 'প্রচুর স্থান ও আরামের সাথে তিন-সারি পারিবারিক SUV।',
// year: 2023,
// mileage: '9,800 km',
// transmission: 'Automatic',
// image: img62,
// },
// {
// id: 63,
// name_en: 'Kia Carnival',
// name_bn: 'কিয়া কার্নিভাল',
// brand: 'Kia',
// model: 'Carnival',
// category: 'MPV',
// price: 19,
// shortDesc_en: 'Spacious MPV ideal for large families and comfortable touring.',
// shortDesc_bn: 'বড় পরিবারের জন্য আদর্শ—বিস্তৃত স্থানের সাথে আরামদায়ক ভ্রমণ।',
// year: 2022,
// mileage: '13,400 km',
// transmission: 'Automatic',
// image: img63,
// },
// {
// transmission: 'Automatic',
// image: img64,
// },
// {
// id: 65,
// name_en: 'Ford EcoSport',
// name_bn: 'ফোর্ড ইকোস্পোর্ট',
// brand: 'Ford',
// model: 'EcoSport',
// category: 'SUV',
// price: 12,
// shortDesc_en: 'Small SUV with city-friendly dimensions and useful features.',
// shortDesc_bn: 'শহুরে ব্যবহারের জন্য উপযোগী আকার ও ব্যবহারিক ফিচারসহ ছোট SUV।',
// year: 2019,
// mileage: '42,000 km',
// transmission: 'Automatic',
// image: img65,
// },
// {
// id: 66,
// name_en: 'Isuzu Trooper',
// name_bn: 'ইসুজু ট্রুপার',
// brand: 'Isuzu',
// model: 'Trooper',
// category: 'SUV',
// price: 10,
// shortDesc_en: 'Simple, rugged SUV designed for utility and low running cost.',
// shortDesc_bn: 'কম চলাফেরার খরচে ব্যবহারযোগ্য ও টেকসই ডিজাইনের SUV।',
// year: 2018,
// mileage: '50,000 km',
// transmission: 'Manual',
// image: img66,
// },
// {
// id: 67,
// name_en: 'BMW X7',
// name_bn: 'বিএমডব্লিউ এক্স৭',
// brand: 'BMW',
// model: 'X7',
// category: 'SUV',
// price: 38,
// shortDesc_en: 'Full-size luxury SUV with powerful engines and executive comfort.',
// shortDesc_bn: 'শক্তিশালী ইঞ্জিন ও এক্সিকিউটিভ কমফোর্টসহ ফুল-সাইজ লাক্সারি SUV।',
// year: 2024,
// mileage: '3,300 km',
// transmission: 'Automatic',
// image: img67,
// },
// {
// id: 68,
// name_en: 'Tesla Model Y',
// name_bn: 'টেসলা মডেল Y',
// brand: 'Tesla',
// model: 'Model Y',
// category: 'Electric',
// price: 33,
// shortDesc_en: 'Versatile electric crossover with excellent range and cargo room.',
// shortDesc_bn: 'চমৎকার রেঞ্জ ও কার্গো রুমসহ বহুমুখী ইলেকট্রিক ক্রসওভার।',
// year: 2023,
// mileage: '6,500 km',
// transmission: 'Automatic',
// image: img68,
// },
// {
// id: 69,
// name_en: 'Audi Q5',
// name_bn: 'অডি Q5',
// brand: 'Audi',
// model: 'Q5',
// category: 'SUV',
// price: 24,
// shortDesc_en: 'All-round compact-luxury SUV with refined dynamics.',
// shortDesc_bn: 'উন্নত ডাইনামিক্স ও লাক্সারি স্পর্শ সহ সবদিক দিয়ে উন্নত SUV।',
// year: 2021,
// mileage: '17,300 km',
// transmission: 'Automatic',
// image: img69,
// },
// {
// name_en: 'Porsche Taycan',
// name_bn: 'পোরশে টাইকান',
// brand: 'Porsche',
// model: 'Taycan',
// category: 'Electric',
// price: 39,
// shortDesc_en: 'High-performance electric sedan with instant torque and handling.',
// shortDesc_bn: 'তাৎক্ষণিক টর্ক ও নির্ভুল হ্যান্ডলিংয়ের সঙ্গে উচ্চ-পারফরম্যান্স ইলেকট্রিক সেডান।',
// year: 2024,
// mileage: '2,600 km',
// transmission: 'Automatic',
// image: img70,
// },
// {
// id: 71,
// name_en: 'Mercedes AMG GT',
// name_bn: 'মার্সিডিজ AMG GT',
// brand: 'Mercedes',
// model: 'AMG GT',
// category: 'Coupe',
// price: 40,
// shortDesc_en: 'High-performance coupe engineered for speed and precision.',
// shortDesc_bn: 'গতি ও নির্ভুলতার জন্য ইঞ্জিনিয়ারড উচ্চ-পারফরম্যান্স কুপে।',
// year: 2020,
// mileage: '10,200 km',
// transmission: 'Automatic',
// image: img71,
// },
// {
// id: 72,
// name_en: 'Lamborghini Gallardo',
// name_bn: 'ল্যাম্বরগিনি গ্যালার্ডো',
// brand: 'Lamborghini',
// model: 'Gallardo',
// category: 'Coupe',
// price: 38,
// shortDesc_en: 'Classic exotic coupe with sharp styling and thrilling performance.',
// shortDesc_bn: 'তীক্ষ্ণ ডিজাইন ও উত্তেজনাপূর্ণ পারফরম্যান্সের ক্লাসিক এক্সোটিক কুপে।',
// year: 2018,
// mileage: '33,000 km',
// transmission: 'Automatic',
// image: img72,
// },
// {
// id: 73,
// name_en: 'Toyota Hilux',
// name_bn: 'টয়োটা হাইলাক্স',
// brand: 'Toyota',
// model: 'Hilux',
// category: 'Truck',
// price: 16,
// shortDesc_en: 'Legendary reliable pickup known for toughness and resale value.',
// shortDesc_bn: 'টেকসই ও ভালো রিসেল ভ্যালু সম্পন্ন কিংবদন্তি পিকআপ ট্রাক।',
// year: 2020,
// mileage: '30,500 km',
// transmission: 'Manual',
// image: img73,
// },
// {
// id: 74,
// name_en: 'Kia Niro',
// name_bn: 'কিয়া নাইরো',
// brand: 'Kia',
// model: 'Niro',
// category: 'Hybrid',
// price: 13,
// shortDesc_en: 'Practical hybrid crossover with efficient fuel consumption.',
// shortDesc_bn: 'কর্মদক্ষ হাইব্রিড ক্রসওভার—সাশ্রয়ী জ্বালানি ব্যবহার।',
// year: 2021,
// mileage: '22,100 km',
// transmission: 'Automatic',
// image: img74,
// },
// {
// id: 75,
// name_en: 'Hyundai Kona',
// name_bn: 'হুন্ডাই কোনা',
// brand: 'Hyundai',
// model: 'Kona',
// category: 'SUV',
// price: 12,
// shortDesc_en: 'Compact crossover with nimble handling and urban agility.',
// shortDesc_bn: 'নিপুণ হ্যান্ডলিং ও শহুরে চালনায় অনুকূল ছোট ক্রসওভার।',
// year: 2022,
// mileage: '15,600 km',
// transmission: 'Automatic',
// image: img75,
// },
// {
// id: 76,
// name_en: 'Nissan Frontier',
// name_bn: 'নিসান ফ্রণ্টিয়ার',
// brand: 'Nissan',
// model: 'Frontier',
// category: 'Truck',
// price: 18,
// shortDesc_en: 'Capable mid-size pickup for both work and light recreation.',
// shortDesc_bn: 'কাজ ও হালকা বিনোদনের উভয়ের জন্য উপযুক্ত মধ্য-মাপের পিকআপ।',
// year: 2019,
// mileage: '28,700 km',
// transmission: 'Manual',
// image: img76,
// },
// {
// id: 77,
// name_en: 'Ford Transit',
// name_bn: 'ফোর্ড ট্রানজিট',
// brand: 'Ford',
// model: 'Transit',
// category: 'Van',
// price: 20,
// shortDesc_en: 'Large-capacity van ideal for cargo, conversion, or shuttle use.',
// shortDesc_bn: 'কার্গো, কনভার্শন বা শাটল ব্যবহারের জন্য উপযুক্ত বৃহৎ-ক্ষমতার ভ্যান।',
// year: 2021,
// mileage: '40,200 km',
// transmission: 'Automatic',
// image: img77,
// },
// {
// id: 78,
// name_en: 'Lucid Air Sapphire',
// name_bn: 'লুসিড এয়ার স্যাফায়ার',
// brand: 'Lucid',
// model: 'Air Sapphire',
// category: 'Electric',
// price: 40,
// shortDesc_en: 'Top-trim Lucid with extreme performance and luxury details.',
// shortDesc_bn: 'চরম পারফরম্যান্স ও বিলাসবহুল বিবরণসহ লুসিডের সর্বোচ্চ ট্রিম।',
// year: 2025,
// mileage: '800 km',
// transmission: 'Automatic',
// image: img78,
// },
// {
// id: 79,
// name_en: 'Rivian R1S Adventure',
// name_bn: 'রিভিয়ান R1S অ্যাডভেঞ্চার',
// brand: 'Rivian',
// model: 'R1S Adventure',
// category: 'SUV',
// price: 36,
// shortDesc_en: 'Spacious electric SUV tailored for outdoor activities and camping.',
// shortDesc_bn: 'আউটডোর কার্যকলাপ ও ক্যাম্পিংকে মাথায় রেখে ডিজাইনকৃত ইলেকট্রিক SUV।',
// year: 2024,
// mileage: '4,100 km',
// transmission: 'Automatic',
// image: img79,
// },
// {
// id: 80,
// name_en: 'Porsche 911 Turbo S',
// name_bn: 'পোরশে ৯১১ টার্বো এস',
// brand: 'Porsche',
// model: '911 Turbo S',
// category: 'Coupe',
// price: 40,
// shortDesc_en: 'Flagship 911 with blistering acceleration and track-capable tech.',
// shortDesc_bn: 'উচ্চগতির ত্বরণ ও ট্র্যাক-ক্ষমতা সম্পন্ন পোরশে ৯১১-এর ফ্ল্যাগশিপ ভার্সন।',
// year: 2025,
// mileage: '500 km',
// transmission: 'Automatic',
// image: img80,
// },
];


export default products;

